import type { LucideIcon } from "lucide-react";
import {
  LayoutDashboard,
  Calculator,
  ClipboardList,
  ChefHat,
  BarChart3,
  Boxes,
  Tag,
  Ticket,
  Users,
  TrendingUp,
  CreditCard,
  BookText,
  Coins,
  FileText,
  UserCheck,
  CalendarDays,
  Store,
  Monitor,
  Truck,
  Settings,
  UserCircle,
  Bell,
  Wallet,
  Box,
  ReceiptText,
  ShoppingBag,
  LogOut,
  ChevronRight,
  ChevronDown,
  Search,
  Plus,
  Filter,
  Download,
} from "lucide-react";

/** Every ICON key from the mockup, mapped to the closest lucide-react icon. */
const ICON_MAP = {
  dashboard: LayoutDashboard,
  cashier: Calculator,
  orders: ClipboardList,
  kitchen: ChefHat,
  report: BarChart3,
  inventory: Boxes,
  product: Tag,
  promo: Ticket,
  customer: Users,
  finance: TrendingUp,
  expense: CreditCard,
  cashbook: BookText,
  payroll: Coins,
  invoice: FileText,
  staff: UserCheck,
  schedule: CalendarDays,
  kasbon: CreditCard,
  business: Store,
  terminal: Monitor,
  online: Truck,
  settings: Settings,
  profile: UserCircle,
  bell: Bell,
  wallet: Wallet,
  cube: Box,
  receiptSm: ReceiptText,
  bag: ShoppingBag,
  truck: Truck,
  card: CreditCard,
  logout: LogOut,
  chevron: ChevronRight,
  chevronDown: ChevronDown,
  search: Search,
  plus: Plus,
  filter: Filter,
  download: Download,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICON_MAP;

/** Port of the mockup's `this.ic(name, size, color, sw)` helper. */
export function ic(
  name: IconName,
  size = 18,
  color = "currentColor",
  sw = 2,
) {
  const Cmp = ICON_MAP[name];
  return <Cmp size={size} color={color} strokeWidth={sw} />;
}
